In [24]:
import duckdb
con = duckdb.connect("hmda.db")

In [25]:
con.sql("DESCRIBE SELECT * FROM 'data/state_NC.csv'")

┌───────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│            column_name            │ column_type │  null   │   key   │ default │  extra  │
│              varchar              │   varchar   │ varchar │ varchar │ varchar │ varchar │
├───────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ activity_year                     │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ lei                               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ derived_msa-md                    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ state_code                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ county_code                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ census_tract                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ conforming_loan_limit             │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ derived_loan_product_type         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ derived_dwelling_category         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ derived_ethnicity                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│        ·                          │   ·         │  ·      │  ·      │  ·      │  ·      │
│        ·                          │   ·         │  ·      │  ·      │  ·      │  ·      │
│        ·                          │   ·         │  ·      │  ·      │  ·      │  ·      │
│ denial_reason-2                   │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ denial_reason-3                   │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ denial_reason-4                   │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_population                  │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_minority_population_percent │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ ffiec_msa_md_median_family_income │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_to_msa_income_percentage    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_owner_occupied_units        │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_one_to_four_family_homes    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ tract_median_age_of_housing_units │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
└───────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  99 rows (20 shown)                                                            6 columns

In [26]:
import pandas as pd
pd.set_option('display.max_rows', None)
con.sql("DESCRIBE SELECT * FROM read_csv('data/state_NC.csv', ignore_errors=true)").df()

,column_name,column_type,null,key,default,extra
0,activity_year,BIGINT,YES,None,None,None
1,lei,VARCHAR,YES,None,None,None
2,derived_msa-md,BIGINT,YES,None,None,None
3,state_code,VARCHAR,YES,None,None,None
4,county_code,VARCHAR,YES,None,None,None
5,census_tract,VARCHAR,YES,None,None,None
6,conforming_loan_limit,VARCHAR,YES,None,None,None
7,derived_loan_product_type,VARCHAR,YES,None,None,None
8,derived_dwelling_category,VARCHAR,YES,None,None,None
9,derived_ethnicity,VARCHAR,YES,None,None,None
10,derived_race,VARCHAR,YES,None,None,None
11,derived_sex,VARCHAR,YES,None,None,None
12,action_taken,BIGINT,YES,None,None,None
13,purchaser_type,BIGINT,YES,None,None,None
14,preapproval,BIGINT,YES,None,None,None
15,loan_type,BIGINT,YES,None,None,None
16,loan_purpose,BIGINT,YES,None,None,None
17,lien_status,BIGINT,YES,None,None,None
18,reverse_mortgage,BIGINT,YES,None,None,None
19,open-end_line_of_credit,BIGINT,YES,None,None,None
20,business_or_commercial_purpose,BIGINT,YES,None,None,None
21,loan_amount,DOUBLE,YES,None,None,None
22,loan_to_value_ratio,VARCHAR,YES,None,None,None
23,interest_rate,VARCHAR,YES,None,None,None
24,rate_spread,VARCHAR,YES,None,None,None
25,hoepa_status,BIGINT,YES,None,None,None
26,total_loan_costs,VARCHAR,YES,None,None,None
27,total_points_and_fees,VARCHAR,YES,None,None,None
28,origination_charges,VARCHAR,YES,None,None,None
29,discount_points,VARCHAR,YES,None,None,None
30,lender_credits,VARCHAR,YES,None,None,None
31,loan_term,VARCHAR,YES,None,None,None
32,prepayment_penalty_term,VARCHAR,YES,None,None,None
33,intro_rate_period,VARCHAR,YES,None,None,None
34,negative_amortization,BIGINT,YES,None,None,None
35,interest_only_payment,BIGINT,YES,None,None,None
36,balloon_payment,BIGINT,YES,None,None,None
37,other_nonamortizing_features,BIGINT,YES,None,None,None
38,property_value,VARCHAR,YES,None,None,None
39,construction_method,BIGINT,YES,None,None,None
40,occupancy_type,BIGINT,YES,None,None,None
41,manufactured_home_secured_property_type,BIGINT,YES,None,None,None
42,manufactured_home_land_property_interest,BIGINT,YES,None,None,None
43,total_units,VARCHAR,YES,None,None,None
44,multifamily_affordable_units,VARCHAR,YES,None,None,None
45,income,VARCHAR,YES,None,None,None
46,debt_to_income_ratio,VARCHAR,YES,None,None,None
47,applicant_credit_score_type,BIGINT,YES,None,None,None
48,co-applicant_credit_score_type,BIGINT,YES,None,None,None
49,applicant_ethnicity-1,BIGINT,YES,None,None,None
50,applicant_ethnicity-2,BIGINT,YES,None,None,None
51,applicant_ethnicity-3,BIGINT,YES,None,None,None
52,applicant_ethnicity-4,VARCHAR,YES,None,None,None
53,applicant_ethnicity-5,VARCHAR,YES,None,None,None
54,co-applicant_ethnicity-1,BIGINT,YES,None,None,None
55,co-applicant_ethnicity-2,BIGINT,YES,None,None,None
56,co-applicant_ethnicity-3,VARCHAR,YES,None,None,None
57,co-applicant_ethnicity-4,VARCHAR,YES,None,None,None
58,co-applicant_ethnicity-5,VARCHAR,YES,None,None,None
59,applicant_ethnicity_observed,BIGINT,YES,None,None,None
60,co-applicant_ethnicity_observed,BIGINT,YES,None,None,None
61,applicant_race-1,BIGINT,YES,None,None,None
62,applicant_race-2,BIGINT,YES,None,None,None
63,applicant_race-3,BIGINT,YES,None,None,None
64,applicant_race-4,BIGINT,YES,None,None,None
65,applicant_race-5,BIGINT,YES,None,None,None
66,co-applicant_race-1,BIGINT,YES,None,None,None
67,co-applicant_race-2,BIGINT,YES,None,None,None
68,co-applicant_race-3,BIGINT,YES,None,None,None
69,co-applicant_race-4,VARCHAR,YES,None,None,None
70,co-applicant_race-5,VARCHAR,YES,None,None,None
71,applicant_race_observed,BIGINT,YES,None,None,None
72,co-applicant_race_observed,BIGINT,YES,None,None,None
73,applicant_sex,BIGINT,YES,None,None,None
74,co-applicant_sex,BIGINT,YES,None,None,None
75,applicant_sex_observed,BIGINT,YES,None,None,None
76,co-applicant_sex_observed,BIGINT,YES,None,None,None
77,applicant_age,VARCHAR,YES,None,None,None
78,co-applicant_age,VARCHAR,YES,None,None,None
79,applicant_age_above_62,VARCHAR,YES,None,None,None
80,co-applicant_age_above_62,VARCHAR,YES,None,None,None
81,submission_of_application,BIGINT,YES,None,None,None
82,initially_payable_to_institution,BIGINT,YES,None,None,None
83,aus-1,BIGINT,YES,None,None,None
84,aus-2,BIGINT,YES,None,None,None
85,aus-3,VARCHAR,YES,None,None,None
86,aus-4,VARCHAR,YES,None,None,None
87,aus-5,VARCHAR,YES,None,None,None
88,denial_reason-1,BIGINT,YES,None,None,None
89,denial_reason-2,BIGINT,YES,None,None,None
90,denial_reason-3,BIGINT,YES,None,None,None
91,denial_reason-4,BIGINT,YES,None,None,None
92,tract_population,BIGINT,YES,None,None,None
93,tract_minority_population_percent,DOUBLE,YES,None,None,None
94,ffiec_msa_md_median_family_income,BIGINT,YES,None,None,None
95,tract_to_msa_income_percentage,BIGINT,YES,None,None,None
96,tract_owner_occupied_units,BIGINT,YES,None,None,None
97,tract_one_to_four_family_homes,BIGINT,YES,None,None,None
98,tract_median_age_of_housing_units,BIGINT,YES,None,None,None

In [27]:
con.sql("""
CREATE OR REPLACE TABLE raw AS
SELECT * FROM read_csv('data/state_NC.csv', ignore_errors=true)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [28]:
con.sql("SELECT * FROM raw LIMIT 5")

┌───────────────┬──────────────────────┬────────────────┬────────────┬─────────────┬──────────────┬───────────────────────┬───────────────────────────┬──────────────────────────────────────┬─────────────────────────┬────────────────────┬───────────────────┬──────────────┬────────────────┬─────────────┬───────────┬──────────────┬─────────────┬──────────────────┬─────────────────────────┬────────────────────────────────┬─────────────┬─────────────────────┬───────────────┬─────────────┬──────────────┬──────────────────┬───────────────────────┬─────────────────────┬─────────────────┬────────────────┬───────────┬─────────────────────────┬───────────────────┬───────────────────────┬───────────────────────┬─────────────────┬──────────────────────────────┬────────────────┬─────────────────────┬────────────────┬─────────────────────────────────────────┬──────────────────────────────────────────┬─────────────┬──────────────────────────────┬─────────┬──────────────────────┬─────────────────────────────┬────────────────────────────────┬───────────────────────┬───────────────────────┬───────────────────────┬───────────────────────┬───────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────────┬─────────────────────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬──────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────────┬────────────────────────────┬───────────────┬──────────────────┬────────────────────────┬───────────────────────────┬───────────────┬──────────────────┬────────────────────────┬───────────────────────────┬───────────────────────────┬──────────────────────────────────┬───────┬───────┬─────────┬─────────┬─────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────────────────────┬───────────────────────────────────┬────────────────────────────────┬────────────────────────────┬────────────────────────────────┬───────────────────────────────────┐
│ activity_year │         lei          │ derived_msa-md │ state_code │ county_code │ census_tract │ conforming_loan_limit │ derived_loan_product_type │      derived_dwelling_category       │    derived_ethnicity    │    derived_race    │    derived_sex    │ action_taken │ purchaser_type │ preapproval │ loan_type │ loan_purpose │ lien_status │ reverse_mortgage │ open-end_line_of_credit │ business_or_commercial_purpose │ loan_amount │ loan_to_value_ratio │ interest_rate │ rate_spread │ hoepa_status │ total_loan_costs │ total_points_and_fees │ origination_charges │ discount_points │ lender_credits │ loan_term │ prepayment_penalty_term │ intro_rate_period │ negative_amortization │ interest_only_payment │ balloon_payment │ other_nonamortizing_features │ property_value │ construction_method │ occupancy_type │ manufactured_home_secured_property_type │ manufactured_home_land_property_interest │ total_units │ multifamily_affordable_units │ income  │ debt_to_income_ratio │ applicant_credit_score_type │ co-applicant_credit_score_type │ applicant_ethnicity-1 │ applicant_ethnicity-2 │ applicant_ethnicity-3 │ applicant_ethnicity-4 │ applicant_ethnicity-5 │ co-applicant_ethnicity-1 │ co-applicant_ethnicity-2 │ co-applicant_ethnicity-3 │ co-applicant_ethnicity-4 │ co-applicant_ethnicity-5 │ applicant_ethnicity_observed │ co-applicant_ethnicity_observed │ applicant_race-1 │ applicant_race-2 │ applicant_race-3 │ applicant_race-4 │ applicant_race-5 │ co-applicant_race-1 │ co-applicant_race-2 │ co-applicant_race-3 │ co-applicant_race-4 │ co-applicant_race-5 │ applicant_race_observed │ co-applicant_race_observed │ applicant_sex │ co-applicant_sex │ applicant_sex_observed │ co-applicant_sex_observed │ applicant_age │ co-applicant_age │ applicant_age_above_62 │ co-applicant_age_above_62 │ submission_of_application │ initially_payable_to_institution │ aus-1 │ aus-2 │  aus-3  │  aus-4  │  aus-5  │ denial_reason-1 │ denial_reason-2 │ denial_reason-3 │ denial_reason-4 │ tract_population │ tract_minority_population_percent │ ffiec_msa_md_median_family_income │ tract_to_msa_income_percentage │ tract_owner_occupied_units │ tract_one_to_four_family_homes │ tract_median_age_of_housing_units │
│     int64     │       varchar        │     int64      │  varchar   │   varchar   │   varchar    │        varchar        │          varchar          │               varchar                │         varchar         │      varchar       │      varchar      │    int64     │     int64      │    int64    │   int64   │    int64     │    int64    │      int64       │          int64          │             int64              │   double    │       varchar       │    varchar    │   varchar   │    int64     │     varchar      │        varchar        │       varchar       │     varchar     │    varchar     │  varchar  │         varchar         │      varchar      │         int64         │         int64         │      int64      │            int64             │    varchar     │        int64        │     int64      │                  int64                  │                  int64                   │   varchar   │           varchar            │ varchar │       varchar        │            int64            │             int64              │         int64         │         int64         │         int64         │        varchar        │        varchar        │          int64           │          int64           │         varchar          │         varchar          │         varchar          │            int64             │              int64              │      int64       │      int64       │      int64       │      int64       │      int64       │        int64        │        int64        │        int64        │       varchar       │       varchar       │          int64          │           int64            │     int64     │      int64       │         int64          │           int64           │    varchar    │     varchar      │        varchar         │          varchar          │           int64           │              int64               │ int64 │ int64 │ varchar │ varchar │ varchar │      int64      │      int64      │      int64      │      int64      │      int64       │              double               │               int64               │             int64              │           int64            │             int64              │               int64               │
├───────────────┼──────────────────────┼────────────────┼────────────┼─────────────┼──────────────┼───────────────────────┼───────────────────────────┼──────────────────────────────────────┼─────────────────────────┼────────────────────┼───────────────────┼──────────────┼────────────────┼─────────────┼───────────┼──────────────┼─────────────┼──────────────────┼─────────────────────────┼────────────────────────────────┼─────────────┼─────────────────────┼───────────────┼─────────────┼──────────────┼──────────────────┼───────────────────────┼─────────────────────┼─────────────────┼────────────────┼───────────┼─────────────────────────┼───────────────────┼───────────────────────┼───────────────────────┼─────────────────┼──────────────────────────────┼────────────────┼─────────────────────┼────────────────┼─────────────────────────────────────────┼──────────────────────────────────────────┼─────────────┼──────────────────────────────┼─────────┼──────────────────────┼─────────────────────────────┼────────────────────────────────┼───────────────────────┼───────────────────────┼───────────────────────┼───────────────────────┼───────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────────┼─────────────────────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────────┼──────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────────┼────────────────────────────┼───────────────┼──────────────────┼────────────────────────┼───────────────────────────┼───────────────┼──────────────────┼────────────────────────┼───────────────────────────┼───────────────────────────┼──────────────────────────────────┼───────┼───────┼─────────┼─────────┼─────────┼─────────────────┼─────────────────┼─────────────────┼─────────────────┼──────────────────┼───────────────────────────────────┼───────────────────────────────────┼────────────────────────────────┼────────────────────────────┼────────────────────────────────┼───────────────────────────────────┤
│          2025 │ 7H6GLXDRUGQFU57RNE97 │          99999 │ NC         │ 37167       │ 37167931203  │ C                     │ Conventional:First Lien   │ Single Family (1-4 Units):Site-Built │ Ethnicity Not Available │ Race Not Available │ Sex Not Available │            6 │              0 │           2 │         1 │           32 │           1 │                2 │                       2 │                              1 │    175000.0 │ NA                  │ 6.625         │ NA          │            3 │ NA               │ NA                    │ NA                  │ NA              │ NA             │ 360       │ NA                      │ NA                │                     2 │                     2 │               2 │                            2 │ 235000         │                   1 │              3 │                                       3 │                                        5 │ 1           │ NA                           │ NA      │ NA                   │                           9 │                              9 │                     4 │                  NULL │                  NULL │ NULL                  │ NULL                  │                        4 │                     NULL │ NULL                     │ NULL                     │ NULL                     │                            3 │                               3 │                7 │             NULL │             NULL │             NULL │             NULL │                   7 │                NULL │                NULL │ NULL                │ NULL                │                       3 │                          3 │             4 │                4 │                      3 │                         3 │ 8888          │ 8888             │ NA                     │ NA                        │                         3 │                                3 │     6 │  NULL │ NULL    │ NULL    │ NULL    │              10 │            NULL │            NULL │            NULL │             2767 │                              77.2 │                             76400 │                              0 │                        454 │                           1347 │                                66 │
│          2025 │ 7H6GLXDRUGQFU57RNE97 │          99999 │ NC         │ 37167       │ 37167931203  │ C                     │ Conventional:First Lien   │ Single Family (1-4 Units):Site-Built │ Ethnicity Not Available │ Race Not Available │ Sex Not Available │            6 │              0 │           2 │         1 │           31 │           1 │                2 │                       2 │                              1 │    165000.0 │ NA                  │ 6.375         │ NA          │            3 │ NA               │ NA                    │ NA                  │ NA              │ NA             │ 360       │ NA                      │ NA                │                     2 │                     2 │               2 │                            2 │ 235000         │                   1 │              3 │                                       3 │                                        5 │ 1           │ NA                           │ NA      │ NA                   │                           9 │                              9 │                     4 │                  NULL │                  NULL │ NULL                  │ NULL                  │                        4 │                     NULL │ NULL                     │ NULL                     │ NULL                     │                            3 │                               3 │                7 │             NULL │             NULL │             NULL │             NULL │                   7 │                NULL │                NULL │ NULL                │ NULL                │                       3 │                          3 │             4 │                4 │                      3 │                         3 │ 8888          │ 8888             │ NA                     │ NA                        │                         3 │                                3 │     6 │  NULL │ NULL    │ NULL    │ NULL    │              10 │            NULL │            NULL │            NULL │             2767 │                              77.2 │                             76400 │                              0 │                        454 │                           1347 │                                66 │
│          2025 │ 7H6GLXDRUGQFU57RNE97 │          24660 │ NC         │ 37151       │ 37151030201  │ C                     │ FHA:First Lien            │ Single Family (1-4 Units):Site-Built │ Ethnicity Not Available │ Race Not Available │ Sex Not Available │            6 │              0 │           2 │         2 │            1 │           1 │                2 │                       2 │                              2 │    145000.0 │ NA                  │ 5.5           │ NA          │            2 │ 0.01             │ NA                    │ 0.01                │ NULL            │ NULL           │ 360       │ NA                      │ NA                │                     2 │                     2 │               2 │                            2 │ 165000         │                   1 │              1 │                                       3 │                                        5 │ 1           │ NA                           │ NA      │ NA                   │                           9 │                              9 │                     4 │                  NULL │                  NULL │ NULL                  │ NULL                  │                        4 │                     NULL │ NULL                     │ NULL                     │ NULL                     │                            3 │                               3 │                7 │             NULL │             NULL │             NULL │             NULL │                   7 │                NULL │                NULL │ NULL                │ NULL                │                       3 │                          3 │             4 │                4 │                      3 │                         3 │ 8888          │ 8888             │ NA                     │ NA                        │                         3 │                                3 │     6 │  NULL │ NULL    │ NULL    │ NULL    │              10 │            NULL │            NULL │            NULL │             3234 │                             36.86 │                             85200 │                             78 │                        810 │                           1417 │                                59 │
│          2025 │ 7H6GLXDRUGQFU57RNE97 │          99999 │ NC         │ 37167       │ 37167931203  │ C                     │ Conventional:First Lien   │ Single Family (1-4 Units):Site-Built │ Ethnicity Not Available │ Race Not Available │ Sex Not Available │            6 │              9 │           2 │         1 │           32 │           1 │                2 │                       2 │                              1 │    165000.0 │ NA                  │ 6.625         │ NA          │            3 │ NA               │ NA                    │ NA                  │ NA              │ NA             │ 360       │ NA                      │ NA                │                     2 │                     2 │               2 │                            2 │ 235000         │                   1 │              3 │                                       3 │                                        5 │ 1           │ NA                           │ NA      │ NA                   │                           9 │                              9 │                     4 │                  NULL │                  NULL │ NULL                  │ NULL                  │                        4 │                     NULL │ NULL                     │ NULL                     │ NULL                     │                            3 │                               3 │                7 │             NULL │             NULL │             NULL │             NULL │                   7 │                NULL │                NULL │ NULL                │ NULL                │                       3 │                          3 │             4 │                4 │                      3 │                         3 │ 8888          │ 8888             │ NA                     │ NA                        │                         3 │                                3 │     6 │  NULL │ NULL    │ NULL    │ NULL    │              10 │            NULL │            NULL │            NULL │             2767 │                              77.2 │                             76400 │                              0 │                        454 │                           1347 │                                66 │
│          2025 │ 7H6GLXDRUGQFU57RNE97 │          99999 │ NC         │ 37181       │ 37181960700  │ C                     │ FHA:First Lien            │ Single Family (1-4 Units):Site-Built │ Ethnicity Not Available │ Race Not Available │ Sex Not Available │            6 │              0 │           2 │         2 │            1 │           1 │                2 │                       2 │                              2 │    125000.0 │ NA                  │ 6.75          │ NA          │            2 │ 0.01             │ NA                    │ 0.01                │ NULL            │ NULL           │ 360       │ NA                      │ NA                │                     2 │                     2 │               2 │                            2 │ 135000         │                   1 │              1 │                                       3 │                                        5 │ 1           │ NA                           │ NA      │ NA                   │                           9 │                              9 │                     4 │                  NULL │                  NULL │ NULL                  │ NULL                  │                        4 │                     NULL │ NULL                     │ NULL                     │ NULL                     │                            3 │                               3 │                7 │             NULL │             NULL │             NULL │             NULL │                   7 │                NULL │                NULL │ NULL                │ NULL                │                       3 │                          3 │             4 │                4 │                      3 │                         3 │ 8888          │ 8888             │ NA                     │ NA                        │                         3 │                                3 │     6 │  NULL │ NULL    │ NULL    │ NULL    │              10 │            NULL │            NULL │            NULL │             3770 │                             92.47 │                             76400 │                             57 │                        426 │                           1707 │                                56 │

In [29]:
con.sql("SELECT action_taken, COUNT(*) FROM raw GROUP BY 1 ORDER BY 2 DESC")

┌──────────────┬──────────────┐
│ action_taken │ count_star() │
│    int64     │    int64     │
├──────────────┼──────────────┤
│            1 │       259717 │
│            3 │        81317 │
│            4 │        62586 │
│            6 │        58717 │
│            5 │        32513 │
│            2 │        15405 │
│            8 │         2565 │
│            7 │          395 │
└──────────────┴──────────────┘

In [ ]:
cols = con.execute("DESCRIBE raw").df()["column_name"].tolist()
results = []
for col in cols:
    q = f"""
    SELECT '{col}' AS column_name,
    COUNT(*) - COUNT("{col}") AS null_count,
    COUNT(DISTINCT "{col}") AS distinct_values,
    FROM raw
"""
    results.append(con.execute(q).df())
profile = pd.concat(results, ignore_index=True)
print(profile)

                                 column_name  null_count  distinct_values  \
0                              activity_year           0                1
1                                        lei           0             1200
2                             derived_msa-md           0               17
3                                 state_code           0                1
4                                county_code           0              101
5                               census_tract           0             2631
6                      conforming_loan_limit           0                3
7                  derived_loan_product_type           0                8
8                  derived_dwelling_category           0                4
9                          derived_ethnicity           0                5
10                              derived_race           0                9
11                               derived_sex           0                4
12                              action_taken           0                8
13                            purchaser_type           0               11
14                               preapproval           0                2
15                                 loan_type           0                4
16                              loan_purpose           0                6
17                               lien_status           0                2
18                          reverse_mortgage           0                3
19                   open-end_line_of_credit           0                3
20            business_or_commercial_purpose           0                3
21                               loan_amount           0              715
22                       loan_to_value_ratio           0            66121
23                             interest_rate           0             3635
24                               rate_spread           0            18465
25                              hoepa_status           0                3
26                          total_loan_costs           0           170378
27                     total_points_and_fees           0             1493
28                       origination_charges           0            94293
29                           discount_points      106918            80872
30                            lender_credits      157115            36392
31                                 loan_term           0              426
32                   prepayment_penalty_term           0               10
33                         intro_rate_period           0               70
34                     negative_amortization           0                3
35                     interest_only_payment           0                3
36                           balloon_payment           0                3
37              other_nonamortizing_features           0                3
38                            property_value           0              790
39                       construction_method           0                2
40                            occupancy_type           0                3
41   manufactured_home_secured_property_type           0                4
42  manufactured_home_land_property_interest           0                6
43                               total_units           0                9
44              multifamily_affordable_units           0               15
45                                    income           0             2489
46                      debt_to_income_ratio           0               21
47               applicant_credit_score_type           0               15
48            co-applicant_credit_score_type           0               16
49                     applicant_ethnicity-1         158                8
50                     applicant_ethnicity-2      495054                6
51                     applicant_ethnicity-3      512778                6
52                     applicant_ethnicity-4      513203                4
53                     applicant_ethnicity-5      513210                3
54                  co-applicant_ethnicity-1          51                9
55                  co-applicant_ethnicity-2      507481                6
56                  co-applicant_ethnicity-3      513085                6
57                  co-applicant_ethnicity-4      513215                0
58                  co-applicant_ethnicity-5      513214                1
59              applicant_ethnicity_observed           0                3
60           co-applicant_ethnicity_observed           0                4
61                          applicant_race-1         100               18
62                          applicant_race-2      492587               16
63                          applicant_race-3      511627               16
64                          applicant_race-4      513027               14
65                          applicant_race-5      513148               12
66                       co-applicant_race-1          28               19
67                       co-applicant_race-2      506818               16
68                       co-applicant_race-3      512738               15
69                       co-applicant_race-4      513160               15
70                       co-applicant_race-5      513196                7
71                   applicant_race_observed           0                3
72                co-applicant_race_observed           0                4
73                             applicant_sex           0                5
74                          co-applicant_sex           0                6
75                    applicant_sex_observed           0                3
76                 co-applicant_sex_observed           0                4
77                             applicant_age           0                8
78                          co-applicant_age           0                9
79                    applicant_age_above_62           0                3
80                 co-applicant_age_above_62           0                3
81                 submission_of_application           0                4
82          initially_payable_to_institution           0                4
83                                     aus-1           0                8
84                                     aus-2      489117                6
85                                     aus-3      506946                5
86                                     aus-4      508958                3
87                                     aus-5      509657                3
88                           denial_reason-1           0               11
89                           denial_reason-2      497158                9
90                           denial_reason-3      510579                9
91                           denial_reason-4      512556                8
92                          tract_population           0             2108
93         tract_minority_population_percent           0             2238
94         ffiec_msa_md_median_family_income           0               17
95            tract_to_msa_income_percentage           0              221
96                tract_owner_occupied_units           0             1402
97            tract_one_to_four_family_homes           0             1591
98         tract_median_age_of_housing_units           0               74

    total_count
0        513215
1        513215
2        513215
3        513215
4        513215
5        513215
6        513215
7        513215
8        513215
9        513215
10       513215
11       513215
12       513215
13       513215
14       513215
15       513215
16       513215
17       513215
18       513215
19       513215
20       513215
21       513215
22       513215
23       513215
24       513215
25       513215
26       513215
27       513215
28       513215
29       513215
30       513215
31       513215
32       513215
33       513215
34       513215
35       513215
36       513215
37       513215
38       513215
39       513215
40       513215
41       513215
42       513215
43       513215
44       513215
45       513215
46       513215
47       513215
48       513215
49       513215
50       513215
51       513215
52       513215
53       513215
54       513215
55       513215
56       513215
57       513215
58       513215
59       513215
60       513215
61       513215
62       513215
63       513215
64       513215
65       513215
66       513215
67       513215
68       513215
69       513215
70       513215
71       513215
72       513215
73       513215
74       513215
75       513215
76       513215
77       513215
78       513215
79       513215
80       513215
81       513215
82       513215
83       513215
84       513215
85       513215
86       513215
87       513215
88       513215
89       513215
90       513215
91       513215
92       513215
93       513215
94       513215
95       513215
96       513215
97       513215
98       513215

In [37]:
con.sql("""
CREATE OR REPLACE TABLE loans AS
SELECT county_code, derived_ethnicity, derived_race, derived_sex, action_taken, purchaser_type, loan_type, loan_amount, interest_rate, loan_to_value_ratio,
income, applicant_credit_score_type, "applicant_ethnicity-1" AS applicant_ethnicity1, "applicant_ethnicity-2" AS applicant_ethnicity2, applicant_ethnicity_observed, "applicant_race-1" AS applicant_race1, applicant_race_observed,
applicant_sex, applicant_sex_observed, applicant_age, "denial_reason-1" AS denial_reason1, "denial_reason-2" AS denial_reason2, "denial_reason-3" AS denial_reason3
FROM raw
""")

con.sql("DESCRIBE SELECT * FROM loans").df()

                     column_name column_type null   key default extra
0                    county_code     VARCHAR  YES  None    None  None
1              derived_ethnicity     VARCHAR  YES  None    None  None
2                   derived_race     VARCHAR  YES  None    None  None
3                    derived_sex     VARCHAR  YES  None    None  None
4                   action_taken      BIGINT  YES  None    None  None
5                 purchaser_type      BIGINT  YES  None    None  None
6                      loan_type      BIGINT  YES  None    None  None
7                    loan_amount      DOUBLE  YES  None    None  None
8                  interest_rate     VARCHAR  YES  None    None  None
9            loan_to_value_ratio     VARCHAR  YES  None    None  None
10                        income     VARCHAR  YES  None    None  None
11   applicant_credit_score_type      BIGINT  YES  None    None  None
12          applicant_ethnicity1      BIGINT  YES  None    None  None
13          applicant_ethnicity2      BIGINT  YES  None    None  None
14  applicant_ethnicity_observed      BIGINT  YES  None    None  None
15               applicant_race1      BIGINT  YES  None    None  None
16       applicant_race_observed      BIGINT  YES  None    None  None
17                 applicant_sex      BIGINT  YES  None    None  None
18        applicant_sex_observed      BIGINT  YES  None    None  None
19                 applicant_age     VARCHAR  YES  None    None  None
20                denial_reason1      BIGINT  YES  None    None  None
21                denial_reason2      BIGINT  YES  None    None  None
22                denial_reason3      BIGINT  YES  None    None  None